version: "3.8"

services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--wiredTigerCacheSizeGB", "0.3"]
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: strongpassword
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      RABBIT_URL: amqp://appuser:strongpassword@rabbitmq:5672
      MONGO_URI: mongodb://mongo:27017/test
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: always

volumes:
  mongo_data:
  rabbitmq_data: